version: "3.9"
services:
  web:
    build: ./containers/nginx
    ports:
      - "8080:80"
    tty: true
    volumes_from:
      - api
    depends_on:
      - api

  api:
    build: .
    volumes:
      - .:/myapp
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
